name: 'Get and cache Python dependencies'
description: 'Get and cache Python dependencies via pip'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  requirements-file:
    description: 'Path to the requirements file'
    required: false
    default: 'devops/requirements/requirements.txt'
  cache-path:
    description: 'Path to cache directory'
    required: false
    default: '~/.cache/pip'
runs:
  using: 'composite'
  steps:
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ runner.os }}-pip-${{ hashFiles(inputs.requirements-file) }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements-file }}
      shell: bash