[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-greeter"
version = "0.1.0"
description = "A simple greeter package"
authors = [{name = "Shubham"}]