name: Build and Deploy src-wheel
on:
  push:
    branches: [dev]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devops/requirements.txt

      - name: Build wheel
        run: |
          rm -rf src-wheel/dist
          cd src-wheel
          python -m build
 
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-greeter
          path: src-wheel/dist/simple_greeter*.whl

  deploy-run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: simple-greeter
          path: dist

      - name: Install wheel artifact
        run: |
          python -m pip install dist/simple_greeter*.whl

      - name: Run app
        run: |
          python src/simple_app.py