name: Test and Run using environment variables
on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:
jobs:
  test-and-run:
    runs-on: ubuntu-latest
    env:
      APP_ENV: 'development'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
  
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('devops/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devops/requirements.txt
      
      - name: Run tests
        id: run-tests
        env:
          APP_ENV: 'test'
        run: |
          # Run tests with coverage         
          PYTHONPATH=src pytest --cov=src tests --cov-report=xml:test-coverage/coverage.xml --cov-report=html:test-coverage/htmlcov --cov-fail-under=70
      
      - name: Upload coverage report
        if: failure() && steps.run-tests.outcome == 'failure' # Only upload if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: test-coverage/
      
      - name: Run app
        run: |
          python src/env_app.py