name: Events activity and filters project
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  test-and-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devops/requirements.txt
      - name: Run tests
        run: |
          PYTHONPATH=src pytest --cov=src tests
      - name: start-app
        run: |
          python src/hello.py