name: Test-project
on: 
  push:
    branches:
      - feature/** #this will only run on feature branches
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devops/requirements.txt
      - name: Run tests
        run: |
          # Run tests with coverage         
          PYTHONPATH=src pytest --cov=src tests